DROP TABLE IF EXISTS LUNCH_GROUP;
DROP TABLE IF EXISTS USER_PROFILE;


CREATE TABLE USER_PROFILE
(
    name        VARCHAR(250) UNIQUE NOT NULL,
    restaurants TEXT                NOT NULL
);

CREATE TABLE LUNCH_GROUP
(
    user1      VARCHAR(250) UNIQUE REFERENCES USER_PROFILE (name),
    user2      VARCHAR(250) UNIQUE REFERENCES USER_PROFILE (name),
    restaurant VARCHAR(250)
);
