### 1. signup 1
// @no-cookie-jar
POST http://localhost:8080/api/lunch/signup
Content-Type: application/json

{
  "name": "test-man1",
  "restaurants": [
    "Il Vesuvio"
  ]
}

### 2. signup 2
POST http://localhost:8080/api/lunch/signup
Content-Type: application/json

{
  "name": "test-man2",
  "restaurants": [
    "Il Vesuvio"
  ]
}

### 3. get status
GET http://localhost:8080/api/lunch/status

### 4. trigger match
POST http://localhost:8080/admin/match

### 5. get match
GET http://localhost:8080/api/lunch/match

### 6. trigger purge
DELETE http://localhost:8080/admin/purge

### 7. get status
GET http://localhost:8080/api/lunch/status

